### ISSUE TITLE
Which pins are used for phase feedback?

### ISSUE THREAD

**Issue by crteensy** [AlkaMotors/AM32_G071#2]
In an earlier design I saw the following pins used for phase feedback:

- A: B.7
- B: B.3
- C: A.2
- Y: A.3

I didn't find definitions for these in the code. Are these pins fixed or is there room for rearrangement?

**Comment by AlkaMotors** [comment]
They are pretty well fixed. These comparator inverting input has very limited pin selection. You can look in the datasheet and any pin that allows comp2 INM can be used but I think these three are the best..and maybe the only ones that will work. There is a pin configuration that works using comp1 and comp2 but then uses one more pin on the MCU overall.

**Comment by crteensy** [comment]
But reordering A,B and C between the pins listed above is ok I guess?

**Comment by AlkaMotors** [comment]
Yes, that's right . You can choose whatever order you like.
